require 'csv'

namespace :species do
  task :fetch, [:filepath] => :environment do |t, args|
    [
      "Aardvark",
      "Aardwolf",
      "Alligator",
      "Alpaca",
      "Anteater",
      "Antelope",
      "Armadillo",
      "Badger",
      "Bandicoot",
      "Bat",
      "Bear",
      "Beaver",
      "Bird",
      "Bison",
      "Bobcat",
      "Camel",
      "Caracal",
      "Cat Domestic",
      "Cheetah",
      "Chinchilla",
      "Chipmunk",
      "Civet",
      "Cougar",
      "Cow",
      "Coyote",
      "Crocodile",
      "Crustacean",
      "Deer",
      "Dingo",
      "Dinosaur",
      "Dodo",
      "Dog Akita",
      "Dog Australian Shepherd",
      "Dog Beagle",
      "Dog Border Collie",
      "Dog Boxer",
      "Dog Bull Terrier",
      "Dog Bulldog",
      "Dog Burnese Mountain",
      "Dog Cattledog",
      "Dog Chow Chow",
      "Dog Collie",
      "Dog Corgi",
      "Dog Dachshund",
      "Dog Dalmatian",
      "Dog Doberman",
      "Dog Domestic",
      "Dog German Shepherd",
      "Dog Golden Retriever",
      "Dog Great Dane",
      "Dog Hound",
      "Dog Husky",
      "Dog Labrador",
      "Dog Malamute",
      "Dog Mixed Breed",
      "Dog Newfoundland",
      "Dog Pitbull",
      "Dog Poodle",
      "Dog Pug",
      "Dog Rottweiler",
      "Dog Samoyed",
      "Dog Sheepdog",
      "Dog Shiba Inu",
      "Dog Spaniel",
      "Dog Terrier",
      "Dolphin",
      "Donkey",
      "Duck",
      "Eagle",
      "Elephant",
      "Extinct Mammal",
      "Fantasy - Alien",
      "Fantasy - Anubis",
      "Fantasy - Cerberus",
      "Fantasy - Chimera",
      "Fantasy - Demon",
      "Fantasy - Digimon",
      "Fantasy - Dragon",
      "Fantasy - Fudog",
      "Fantasy - Gargoyle",
      "Fantasy - Golem",
      "Fantasy - Gremlin",
      "Fantasy - Gryphon",
      "Fantasy - Kirin",
      "Fantasy - Kitsune",
      "Fantasy - Malluch",
      "Fantasy - Mechanical",
      "Fantasy - Media",
      "Fantasy - Minotaur",
      "Fantasy - Monster",
      "Fantasy - Phoenix",
      "Fantasy - Pokemon",
      "Fantasy - Undead",
      "Fantasy - Unicorn",
      "Fantasy - Werewolf",
      "Fantasy - Wickerbeast",
      "Fantasy - Yeti",
      "Fennec",
      "Ferret",
      "Fish",
      "Fox",
      "Frog",
      "Gecko",
      "Genet",
      "Gerbil",
      "Giraffe",
      "Goat",
      "Guinea Pig",
      "Hamster",
      "Hare",
      "Hawk",
      "Hedgehog",
      "Hippopotamus",
      "Horse",
      "Hybrid Angel Dragon",
      "Hybrid Cabbit",
      "Hybrid Cannax",
      "Hybrid Cat-Fox",
      "Hybrid Chimera",
      "Hybrid Crux",
      "Hybrid Custom",
      "Hybrid Dragon Fox",
      "Hybrid Drusky",
      "Hybrid Dutch Angel Dragon",
      "Hybrid Folf",
      "Hybrid Fox Bat",
      "Hybrid Foxcoon",
      "Hybrid Fusky",
      "Hybrid Jackalope",
      "Hybrid Liger/Tigon",
      "Hybrid Manokit",
      "Hybrid Pandacat",
      "Hybrid Protogen",
      "Hybrid Sergal",
      "Hybrid Tiger Dragon",
      "Hybrid Wolf Fox",
      "Hybrid Wolf Shark",
      "Hybrid Wolfcoon",
      "Hybrid Wolfdog",
      "Hybrid Wolgen/Drolf",
      "Hybrid Wolger",
      "Hybrid Wusky/Wolfsky",
      "Hyena",
      "Insect",
      "Jackal",
      "Jaguar",
      "Kangaroo",
      "Koala",
      "Lemur",
      "Leopard",
      "Lion",
      "Lizard",
      "Llama",
      "Lynx",
      "Maned Wolf",
      "Marten",
      "Meerkat",
      "Mink",
      "Mole",
      "Mongoose",
      "Monkey",
      "Moose",
      "Mouse",
      "Ocelot",
      "Okapi",
      "Orca",
      "Other (Contact Support)",
      "Otter",
      "Owl",
      "Panda",
      "Panther",
      "Parrot",
      "Pig",
      "Platypus",
      "Polar Bear",
      "Pony",
      "Porcupine",
      "Possum",
      "Primate",
      "Puffin",
      "Rabbit",
      "Raccoon",
      "Rat",
      "Red Panda",
      "Rhinoceros",
      "Salamander",
      "Sand Dune Cat",
      "Seal",
      "Serval",
      "Shark",
      "Sheep",
      "Skunk",
      "Sloth",
      "Snake",
      "Snow Leopard",
      "Squirrel",
      "Sugar Glider",
      "Tanuki",
      "Tapir",
      "Tasmanian Devil",
      "Tiger",
      "Toad",
      "Turtle",
      "Weasel",
      "Wild Boar",
      "Wild Cat",
      "Wild Dog",
      "Wildebeest",
      "Wolf",
      "Wolverine",
      "Zebra"
    ].each do |e|
      Specy.create!(name: e)
    end
  end
end

require 'csv'

namespace :species_rake do
  task :fetch_icons, [:filepath] => :environment do |t, args|
    [
      {name: "Aardvark", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Aardwolf", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Alligator", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Alpaca", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Anteater", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Antelope", icon: "Antelope"},
      {name: "Armadillo", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Badger", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Bandicoot", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Bat", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Bear", icon: "Bear"},
      {name: "Beaver", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Bird", icon: "Bird (Small)"},
      {name: "Bison", icon: "Cow (Bull)"},
      {name: "Bobcat", icon: "Bobcat"},
      {name: "Camel", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Caracal", icon: "Lynx"},
      {name: "Cat Domestic", icon: "Domestic Cat"},
      {name: "Cheetah", icon: "Spotted Cat"},
      {name: "Chinchilla", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Chipmunk", icon: "Squirrel"},
      {name: "Civet", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Cougar", icon: "Feline (Long Tail)"},
      {name: "Cow", icon: "Cow (Bull)"},
      {name: "Coyote", icon: "Dog Thick Tail"},
      {name: "Crocodile", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Crustacean", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Deer", icon: "Deer"},
      {name: "Dingo", icon: "Dog Thick Tail"},
      {name: "Dinosaur", icon: "Extinct"},
      {name: "Dodo", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Dog Akita", icon: "Dog Thick Tail"},
      {name: "Dog Australian Shepherd", icon: "Dog Half Cocked Medium Tail"},
      {name: "Dog Beagle", icon: "Dog Both Cocked Thin Tail"},
      {name: "Dog Border Collie", icon: "Dog Half Cocked Medium Tail"},
      {name: "Dog Boxer", icon: "Dog Both Cocked Thin Tail"},
      {name: "Dog Bull Terrier", icon: "Wolverine"},
      {name: "Dog Bulldog", icon: "Dog Both Cocked Stub Tail"},
      {name: "Dog Burnese Mountain", icon: "Dog Half Cocked Medium Tail"},
      {name: "Dog Cattledog", icon: "Dog Medium Tail"},
      {name: "Dog Chow Chow", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Dog Collie", icon: "Dog Half Cocked Medium Tail"},
      {name: "Dog Corgi", icon: "Dog Half Cocked Stub Tail"},
      {name: "Dog Dachshund", icon: "Dog Both Cocked Thin Tail"},
      {name: "Dog Dalmatian", icon: "Dalmation"},
      {name: "Dog Doberman", icon: "Dog Half Cocked Stub Tail"},
      {name: "Dog Domestic", icon: "Dog Half Cocked Stub Tail"},
      {name: "Dog German Shepherd", icon: "Dog Thick Tail"},
      {name: "Dog Golden Retriever", icon: "Dog Half Cocked Medium Tail"},
      {name: "Dog Great Dane", icon: "Dog Both Cocked Thin Tail"},
      {name: "Dog Hound", icon: "Dog Both Cocked Thin Tail"},
      {name: "Dog Husky", icon: "Husky"},
      {name: "Dog Labrador", icon: "Dog Half Cocked Medium Tail"},
      {name: "Dog Malamute", icon: "Husky"},
      {name: "Dog Mixed Breed", icon: "Dog Half Cocked Medium Tail"},
      {name: "Dog Newfoundland", icon: "Dog Both Cocked Stub Tail"},
      {name: "Dog Pitbull", icon: "Dog Half Cocked Stub Tail"},
      {name: "Dog Poodle", icon: "Dog Both Cocked Stub Tail"},
      {name: "Dog Pug", icon: "Dog Both Cocked Stub Tail"},
      {name: "Dog Rottweiler", icon: "Dog Half Cocked Stub Tail"},
      {name: "Dog Samoyed", icon: "Dog Thick Tail"},
      {name: "Dog Sheepdog", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Dog Shiba Inu", icon: "Dog Medium Tail"},
      {name: "Dog Spaniel", icon: "Dog Both Cocked Thin Tail"},
      {name: "Dog Terrier", icon: "Dog Half Cocked Stub Tail"},
      {name: "Dolphin", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Donkey", icon: "Horse"},
      {name: "Duck", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Eagle", icon: "Bird (Large)"},
      {name: "Elephant", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Extinct Mammal", icon: "Extinct"},
      {name: "Fantasy - Alien", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fantasy - Anubis", icon: "Dog Thick Tail"},
      {name: "Fantasy - Cerberus", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fantasy - Chimera", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fantasy - Demon", icon: "Cow (Bull)"},
      {name: "Fantasy - Digimon", icon: "Media"},
      {name: "Fantasy - Dragon", icon: "Dragon"},
      {name: "Fantasy - Fudog", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fantasy - Gargoyle", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fantasy - Golem", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fantasy - Gremlin", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fantasy - Gryphon", icon: "Gryphon"},
      {name: "Fantasy - Kirin", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fantasy - Kitsune", icon: "Hybrid"},
      {name: "Fantasy - Malluch", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fantasy - Mechanical", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fantasy - Media", icon: "Media"},
      {name: "Fantasy - Minotaur", icon: "Chimera"},
      {name: "Fantasy - Monster", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fantasy - Phoenix", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fantasy - Pokemon", icon: "Media"},
      {name: "Fantasy - Undead", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fantasy - Unicorn", icon: "Unicorn"},
      {name: "Fantasy - Werewolf", icon: "Wolf"},
      {name: "Fantasy - Wickerbeast", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fantasy - Yeti", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fennec", icon: "Fennec"},
      {name: "Ferret", icon: "Ferret"},
      {name: "Fish", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Fox", icon: "Fox"},
      {name: "Frog", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Gecko", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Genet", icon: "Genet"},
      {name: "Gerbil", icon: "Guinea Pig (Hamster)"},
      {name: "Giraffe", icon: "Giraffe"},
      {name: "Goat", icon: "Goat"},
      {name: "Guinea Pig", icon: "Guinea Pig (Hamster)"},
      {name: "Hamster", icon: "Guinea Pig (Hamster)"},
      {name: "Hare", icon: "Rabbit"},
      {name: "Hawk", icon: "Bird (Large)"},
      {name: "Hedgehog", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Hippopotamus", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Horse", icon: "Horse"},
      {name: "Hybrid Angel Dragon", icon: "Angel Dragon"},
      {name: "Hybrid Cabbit", icon: "Hybrid"},
      {name: "Hybrid Cannax", icon: "Hybrid"},
      {name: "Hybrid Cat-Fox", icon: "Hybrid"},
      {name: "Hybrid Chimera", icon: "Hybrid"},
      {name: "Hybrid Crux", icon: "Hybrid"},
      {name: "Hybrid Custom", icon: "Hybrid"},
      {name: "Hybrid Dragon Fox", icon: "Hybrid"},
      {name: "Hybrid Drusky", icon: "Hybrid"},
      {name: "Hybrid Dutch Angel Dragon", icon: "Angel Dragon"},
      {name: "Hybrid Folf", icon: "Hybrid"},
      {name: "Hybrid Fox Bat", icon: "Hybrid"},
      {name: "Hybrid Foxcoon", icon: "Hybrid"},
      {name: "Hybrid Fusky", icon: "Hybrid"},
      {name: "Hybrid Jackalope", icon: "Hybrid"},
      {name: "Hybrid Liger/Tigon", icon: "Hybrid"},
      {name: "Hybrid Manokit", icon: "Hybrid"},
      {name: "Hybrid Pandacat", icon: "Hybrid"},
      {name: "Hybrid Protogen", icon: "Hybrid"},
      {name: "Hybrid Sergal", icon: "Hybrid"},
      {name: "Hybrid Tiger Dragon", icon: "Hybrid"},
      {name: "Hybrid Wolf Fox", icon: "Hybrid"},
      {name: "Hybrid Wolf Shark", icon: "Hybrid"},
      {name: "Hybrid Wolfcoon", icon: "Hybrid"},
      {name: "Hybrid Wolfdog", icon: "Hybrid"},
      {name: "Hybrid Wolgen/Drolf", icon: "Hybrid"},
      {name: "Hybrid Wolger", icon: "Hybrid"},
      {name: "Hybrid Wusky/Wolfsky", icon: "Hybrid"},
      {name: "Hyena", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Insect", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Jackal", icon: "Dog Thick Tail"},
      {name: "Jaguar", icon: "Spotted Cat"},
      {name: "Kangaroo", icon: "Kangaroo"},
      {name: "Koala", icon: "Bear"},
      {name: "Lemur", icon: "Red Panda"},
      {name: "Leopard", icon: "Snow Leopard"},
      {name: "Lion", icon: "Lion"},
      {name: "Lizard", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Llama", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Lynx", icon: "Lynx"},
      {name: "Maned Wolf", icon: "Fox"},
      {name: "Marten", icon: "Mustelidae (Weasel, Meerkat etc)"},
      {name: "Meerkat", icon: "Mustelidae (Weasel, Meerkat etc)"},
      {name: "Mink", icon: "Mustelidae (Weasel, Meerkat etc)"},
      {name: "Mole", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Mongoose", icon: "Mustelidae (Weasel, Meerkat etc)"},
      {name: "Monkey", icon: "Primate"},
      {name: "Moose", icon: "Deer"},
      {name: "Mouse", icon: "Mouse (Rat)"},
      {name: "Ocelot", icon: "Spotted Cat"},
      {name: "Okapi", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Orca", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Other (Contact Support)", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Otter", icon: "Mustelidae (Weasel, Meerkat etc)"},
      {name: "Owl", icon: "Bird (Large)"},
      {name: "Panda", icon: "Bear"},
      {name: "Panther", icon: "Feline (Long Tail)"},
      {name: "Parrot", icon: "Bird (Large)"},
      {name: "Pig", icon: "Pig"},
      {name: "Platypus", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Polar Bear", icon: "Bear"},
      {name: "Pony", icon: "Horse"},
      {name: "Porcupine", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Possum", icon: "Mustelidae (Weasel, Meerkat etc)"},
      {name: "Primate", icon: "Primate"},
      {name: "Puffin", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Rabbit", icon: "Rabbit"},
      {name: "Raccoon", icon: "Raccoon"},
      {name: "Rat", icon: "Mouse (Rat)"},
      {name: "Red Panda", icon: "Red Panda"},
      {name: "Rhinoceros", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Salamander", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Sand Dune Cat", icon: "Feline (Long Tail)"},
      {name: "Seal", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Serval", icon: "Serval"},
      {name: "Shark", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Sheep", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Skunk", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Sloth", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Snake", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Snow Leopard", icon: "Snow Leopard"},
      {name: "Squirrel", icon: "Squirrel"},
      {name: "Sugar Glider", icon: "Mustelidae (Weasel, Meerkat etc)"},
      {name: "Tanuki", icon: "Tanuki"},
      {name: "Tapir", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Tasmanian Devil", icon: "Wolverine"},
      {name: "Tiger", icon: "Tiger"},
      {name: "Toad", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Turtle", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Weasel", icon: "Mustelidae (Weasel, Meerkat etc)"},
      {name: "Wild Boar", icon: "Pig"},
      {name: "Wild Cat", icon: "Feline (Long Tail)"},
      {name: "Wild Dog", icon: "Spotted Dog"},
      {name: "Wildebeest", icon: "Cow (Bull)"},
      {name: "Wolf", icon: "Wolf"},
      {name: "Wolverine", icon: "Missingno (No Avatar Graphic Found)"},
      {name: "Zebra", icon: "Zebra"}
    ].each do |e|
      begin
        Specy.find_by(name: e[:name]).update!(avatar_file: e[:icon])
      rescue => error
        TechReport.create!(user: User.first, kind: "exception", description: "Species Icon Rake: #{e[:name]}")
      end
    end
  end
end
