require 'csv'

namespace :species do
  task :fetch, [:filepath] => :environment do |t, args|
    [
      "Aardvark",
      "Aardwolf",
      "Alligator",
      "Alpaca",
      "Anteater",
      "Antelope",
      "Armadillo",
      "Badger",
      "Bandicoot",
      "Bat",
      "Bear",
      "Beaver",
      "Bird",
      "Bison",
      "Bobcat",
      "Camel",
      "Caracal",
      "Cat Domestic",
      "Cheetah",
      "Chinchilla",
      "Chipmunk",
      "Civet",
      "Cougar",
      "Cow",
      "Coyote",
      "Crocodile",
      "Crustacean",
      "Deer",
      "Dingo",
      "Dinosaur",
      "Dodo",
      "Dog Akita",
      "Dog Australian Shepherd",
      "Dog Beagle",
      "Dog Border Collie",
      "Dog Boxer",
      "Dog Bull Terrier",
      "Dog Bulldog",
      "Dog Burnese Mountain",
      "Dog Cattledog",
      "Dog Chow Chow",
      "Dog Collie",
      "Dog Corgi",
      "Dog Dachshund",
      "Dog Dalmatian",
      "Dog Doberman",
      "Dog Domestic",
      "Dog German Shepherd",
      "Dog Golden Retriever",
      "Dog Great Dane",
      "Dog Hound",
      "Dog Husky",
      "Dog Labrador",
      "Dog Malamute",
      "Dog Mixed Breed",
      "Dog Newfoundland",
      "Dog Pitbull",
      "Dog Poodle",
      "Dog Pug",
      "Dog Rottweiler",
      "Dog Samoyed",
      "Dog Sheepdog",
      "Dog Shiba Inu",
      "Dog Spaniel",
      "Dog Terrier",
      "Dolphin",
      "Donkey",
      "Duck",
      "Eagle",
      "Elephant",
      "Extinct Mammal",
      "Fantasy - Alien",
      "Fantasy - Anubis",
      "Fantasy - Cerberus",
      "Fantasy - Chimera",
      "Fantasy - Demon",
      "Fantasy - Digimon",
      "Fantasy - Dragon",
      "Fantasy - Fudog",
      "Fantasy - Gargoyle",
      "Fantasy - Golem",
      "Fantasy - Gremlin",
      "Fantasy - Gryphon",
      "Fantasy - Kirin",
      "Fantasy - Malluch",
      "Fantasy - Mechanical",
      "Fantasy - Media",
      "Fantasy - Minotaur",
      "Fantasy - Monster",
      "Fantasy - Phoenix",
      "Fantasy - Pokemon",
      "Fantasy - Undead",
      "Fantasy - Unicorn",
      "Fantasy - Werewolf",
      "Fantasy - Wickerbeast",
      "Fantasy - Yeti",
      "Fennec",
      "Ferret",
      "Fish",
      "Fox",
      "Frog",
      "Gecko",
      "Genet",
      "Gerbil",
      "Giraffe",
      "Goat",
      "Guinea Pig",
      "Hamster",
      "Hare",
      "Hawk",
      "Hedgehog",
      "Hippopotamus",
      "Horse",
      "Hybrid Angel Dragon",
      "Hybrid Cabbit",
      "Hybrid Cannax",
      "Hybrid Cat-Fox",
      "Hybrid Chimera",
      "Hybrid Crux",
      "Hybrid Custom",
      "Hybrid Dragon Fox",
      "Hybrid Drusky",
      "Hybrid Dutch Angel Dragon",
      "Hybrid Folf",
      "Hybrid Fox Bat",
      "Hybrid Foxcoon",
      "Hybrid Fusky",
      "Hybrid Jackalope",
      "Hybrid Kitsune",
      "Hybrid Liger/Tigon",
      "Hybrid Manokit",
      "Hybrid Pandacat",
      "Hybrid Protogen",
      "Hybrid Sergal",
      "Hybrid Sergal",
      "Hybrid Tiger Dragon",
      "Hybrid Wolf Fox",
      "Hybrid Wolf Shark",
      "Hybrid Wolfcoon",
      "Hybrid Wolfdog",
      "Hybrid Wolgen/Drolf",
      "Hybrid Wolger",
      "Hybrid Wusky/Wolfsky",
      "Hyena",
      "Insect",
      "Jackal",
      "Jaguar",
      "Kangaroo",
      "Koala",
      "Lemur",
      "Leopard",
      "Lion",
      "Lizard",
      "Llama",
      "Lynx",
      "Maned Wolf",
      "Marten",
      "Meerkat",
      "Mink",
      "Mole",
      "Mongoose",
      "Monkey",
      "Moose",
      "Mouse",
      "Ocelot",
      "Okapi",
      "Orca",
      "Other (Contact Support)",
      "Otter",
      "Owl",
      "Panda",
      "Panther",
      "Parrot",
      "Pig",
      "Platypus",
      "Polar Bear",
      "Pony",
      "Porcupine",
      "Possum",
      "Primate",
      "Puffin",
      "Rabbit",
      "Raccoon",
      "Rat",
      "Red Panda",
      "Rhinoceros",
      "Salamander",
      "Sand Dune Cat",
      "Seal",
      "Serval",
      "Shark",
      "Sheep",
      "Skunk",
      "Sloth",
      "Snake",
      "Snow Leopard",
      "Squirrel",
      "Sugar Glider",
      "Tanuki",
      "Tapir",
      "Tasmanian Devil",
      "Tiger",
      "Toad",
      "Turtle",
      "Weasel",
      "Wild Boar",
      "Wild Cat",
      "Wild Dog",
      "Wildebeest",
      "Wolf",
      "Wolverine",
      "Zebra"
    ].each do |e|
      Specy.create!(name: e)
    end
  end
end
