// eslint-disable-line
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
    purge: [],
    future: {
        removeDeprecatedGapUtilities: true,
        purgeLayersByDefault: true,
    },
    theme: {
        extend: {
            fontSize: {
                xxs: '0.625rem',
            },
            padding: {
                A4: '2.5cm',
                '1/2': '50%',
            },
            colors: {
                dark: {
                    100: '#4C566A',
                    // 200: "",
                    300: '#434C5E',
                    // 400: "",
                    500: '#3B4252',
                    // 600: "",
                    700: '#2E3440',
                    // 800: "",
                    900: '#05050A',
                },
                light: {
                    0: '#f8f9fb',
                    100: '#ECEFF4',
                    // 200: "",
                    300: '#E5E9F0',
                    // 400: "",
                    500: '#D8DEE9',
                    // 600: "",
                    700: '#A8AEA9',
                    // 800: "",
                    900: '#6B778C',
                },
                primary: {
                    100: '#eef2f6',
                    200: '#cdd7e5',
                    300: '#abbdd4',
                    400: '#89a3c2',
                    500: '#0c8cff',
                    600: '#4e6f97',
                    700: '#3d5676',
                    800: '#2b3e54',
                    900: '#1a2532',
                },
                secondary: {
                    100: '#eef2f7',
                    200: '#ccd9e6',
                    300: '#aabfd5',
                    400: '#87a6c4',
                    500: '#81A1C1',
                    600: '#4c739a',
                    700: '#3b5978',
                    800: '#2a4055',
                    900: '#192633',
                },
                accent: {
                    100: '#a5c9c9',
                    // 200: "",
                    300: '#a5c9c9',
                    // 400: "",
                    500: '#8FBCBB',
                    // 600: "",
                    700: '#729696',
                    // 800: "",
                    900: '#567170',
                },
                error: {
                    100: '#f8edee',
                    200: '#e9c9cc',
                    300: '#daa4a9',
                    400: '#cc8087',
                    500: '#BF616A',
                    600: '#a3424b',
                    700: '#7f333b',
                    800: '#5b252a',
                    900: '#361619',
                },
                danger: {
                    100: '#f9efec',
                    200: '#eccfc5',
                    300: '#dfae9f',
                    400: '#d38e79',
                    500: '#D08770',
                    600: '#ad5539',
                    700: '#86422c',
                    800: '#602f20',
                    900: '#3a1c13',
                },
                warning: {
                    100: '#fbf5e9',
                    200: '#f4e2be',
                    300: '#ecce92',
                    400: '#e5bb67',
                    500: '#EBCB8B',
                    600: '#c48e22',
                    700: '#986e1a',
                    800: '#6d4f13',
                    900: '#412f0b',
                },
                success: {
                    100: '#f2f6ef',
                    200: '#d8e3ce',
                    300: '#bed1ae',
                    400: '#a4bf8d',
                    500: '#A3BE8C',
                    600: '#709353',
                    700: '#577240',
                    800: '#3e512e',
                    900: '#25311c',
                },
                help: {
                    100: '#f5f0f4',
                    // 200: "",
                    300: '#c3a5bd',
                    // 400: "",
                    500: '#B48EAD',
                    // 600: "",
                    700: '#90728a',
                    // 800: "",
                    900: '#6c5568',
                },
            },
            width: {
                A4: '21cm',
            },
            maxWidth: {
                xxxs: '12rem',
                xxs: '16rem',
                h1: '50ch',
                h2: '60ch',
                h3: '60ch',
                h4: '65ch',
                h5: '70ch',
                h6: '75ch',
                paragraph: '90ch',
                '7xl': '80rem',
                A4: '21cm',
            },
            fontFamily: {
                cute: ['"Yusei Magic"', 'sans-serif'],
                sans: ['"Nunito"', 'sans-serif'],
            },
            height: {
                72: '20rem',
                80: '24rem',
            },
            minHeight: {
                A4: '29.7cm',
                xxxs: '12rem',
                xxs: '16rem',
                xs: '20rem',
                sm: '24rem',
                md: '28rem',
                lg: '32rem',
                xl: '36rem',
                layout: 'calc(100vh - 4rem)',
            },
            minWidth: {
                xxxs: '12rem',
                xxs: '16rem',
                xs: '20rem',
                sm: '24rem',
                md: '28rem',
                lg: '32rem',
                xl: '36rem',
            },
            boxShadow: {
                'outline-primary': '0 0 0 3px rgba(75, 103, 138, 0.5);',
            },
            gridTemplateColumns: {
                scrollable: 'repeat(200, 16rem)',
            },
        },
    },
    variants: {
        textColor: ['responsive', 'hover', 'focus', 'group-hover', 'disabled'],
        background: ['responsive', 'hover', 'focus', 'group-hover', 'group-focus', 'disabled'],
        backgroundColor: ['responsive', 'hover', 'focus', 'group-hover', 'group-focus', 'disabled'],
        fontWeight: ['responsive', 'hover', 'focus', 'group-hover'],
        boxShadow: ['responsive', 'hover', 'focus', 'group-hover', 'group-focus', 'focus-within'],
        padding: ['first'],
        display: ['responsive', 'hover', 'focus', 'group-hover', 'group-focus'],
        opacity: ['responsive', 'hover', 'focus', 'disabled'],
        pointerEvents: ['responsive', 'disabled'],
        cursor: ['disabled'],
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('@tailwindcss/aspect-ratio'),
    ],
}
